### ISSUE TITLE
0_default-game-content/textures/crcity/ should probably be moved to 0_default-hdtextures

### ISSUE THREAD

**Issue by MVarland** [actionquake/distrib#259]
Also should the .jpg files be removed since we only provide .png for the hd textures pack?

**Comment by darkshade9** [comment]
Because the engine doesn't know to download specific file extensions, and because it supports three (four, counting .wal files), what I've done is found all HD textures that are PNG files and included them in the distro, and all JPG files are downloaded via the downloadserver.  WAL files are also downloaded along with JPG.

**Comment by darkshade9** [comment]
These textures have been moved to hdtextures
